alias v="nvim"
#alias sway="sway --unsupported-gpu"
#alias sway="sway"
alias reboot="loginctl reboot"
alias shutdown="loginctl poweroff"
#alias backports="sudo apt -t daedalus-backports install"
alias update="sudo apt update && sudo apt upgrade && flatpak update"
alias clean="sudo apt clean && sudo apt autoclean && sudo apt autoremove"
